name: Publish Nahl.NetCore.HealthChecks

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
        - uses: actions/checkout@v2

        - name: Setup .NET Core
          uses: actions/setup-dotnet@v1
          with:
            dotnet-version: 3.1.301

        - name: Install dependencies
          run: dotnet restore src/Nahl.NetCore.HealthChecks.sln

        - name: Build
          run: dotnet build src/Nahl.NetCore.HealthChecks.sln --configuration Release --no-restore

        - name: Publish Nahl.NetCore.HealthChecks
          uses: brandedoutcast/publish-nuget@v2.5.2
          with:
            PROJECT_FILE_PATH: src/Nahl.NetCore.HealthChecks/Nahl.NetCore.HealthChecks.csproj
            NUGET_KEY: ${{secrets.NUGET_API_KEY}}
            NUGET_SOURCE: https://api.nuget.org
